version: '3'

services:
  cpx:
    image: store/citrix/netscalercpx:12.0-56.20
    ports:
      - 22
      - "127.0.0.1:8080:8088"
      - 80
    tty: true
    container_name: cpx
    privileged: true
    environment:
      - EULA=yes

  cpx-sidecar:
    image: cpx-consul-sidecar
    container_name: cpx-sidecar
    depends_on:
      - cpx
    environment:
      - NS_PORT=80
      - NS_IP=cpx
      - CONSUL_IP=${HOST_IP}
